import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#f8faf9' },
  screen: { flex: 1, backgroundColor: '#fbfcfc' },
  container: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 112 },
  topBar: { height: 70, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  leftTopActions: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  screenTitle: { position: 'absolute', left: 0, right: 0, top: 24, textAlign: 'center', fontSize: 24, fontWeight: '900', color: '#0f2233' },
  headerIcon: { width: 40, height: 40, borderRadius: 14, backgroundColor: '#fff', borderWidth: 1, borderColor: '#edf0f2', alignItems: 'center', justifyContent: 'center', shadowColor: '#0f172a', shadowOpacity: 0.04, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, elevation: 1, zIndex: 2 },
  headerIconText: { color: '#081525', fontSize: 18, fontWeight: '800', lineHeight: 21 },
  headerBackText: { fontSize: 26, lineHeight: 28, marginTop: -1 },
  searchBox: { marginTop: 6, height: 48, borderRadius: 18, backgroundColor: '#fff', borderWidth: 1, borderColor: '#e7ecef', flexDirection: 'row-reverse', alignItems: 'center', paddingHorizontal: 14 },
  searchInput: { flex: 1, textAlign: 'right', color: '#0f172a', fontWeight: '800', paddingVertical: 8 },
  searchGlyph: { color: '#0f766e', fontSize: 18, fontWeight: '900', marginLeft: 8 },
  summaryRow: { marginTop: 14, flexDirection: 'row', gap: 10 },
  summaryCard: { flex: 1, minHeight: 138, borderRadius: 22, paddingVertical: 15, paddingHorizontal: 8, alignItems: 'center', borderWidth: 1, borderColor: '#e4ebea', shadowColor: '#1f2937', shadowOpacity: 0.04, shadowRadius: 10, shadowOffset: { width: 0, height: 5 }, elevation: 1 },
  summaryGreen: { backgroundColor: '#f2fbf8' },
  summaryGold: { backgroundColor: '#fffaf1' },
  summaryTeal: { backgroundColor: '#f2fbf9' },
  summaryIcon: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center', marginBottom: 12, shadowColor: '#111827', shadowOpacity: 0.14, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 3 },
  greenCircle: { backgroundColor: '#35b95a' },
  goldCircle: { backgroundColor: '#deb33c' },
  tealCircle: { backgroundColor: '#18a99a' },
  summaryIconText: { color: '#fff', fontSize: 19, fontWeight: '900' },
  summaryLabel: { color: '#0f1f2e', fontSize: 10.5, fontWeight: '800', textAlign: 'center', marginBottom: 5, lineHeight: 18 },
  valueLine: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'center', gap: 3 },
  currencyText: { color: '#0f172a', fontSize: 9.5, fontWeight: '800' },
  summaryValue: { color: '#0b1726', fontSize: 18, fontWeight: '900', textAlign: 'center' },
  summarySuffix: { color: '#334155', fontSize: 10, fontWeight: '700', marginTop: 1 },
  filterShell: { marginTop: 24, minHeight: 57, borderRadius: 24, backgroundColor: '#fff', borderWidth: 1, borderColor: '#e4e8eb', flexDirection: 'row-reverse', alignItems: 'center', padding: 5, shadowColor: '#111827', shadowOpacity: 0.035, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 1 },
  filterSegment: { flex: 1, height: 47, borderRadius: 20, flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'center', gap: 8 },
  allFilterSegment: { flex: 1.22 },
  filterSegmentActive: { backgroundColor: '#006168' },
  filterDot: { width: 8, height: 8, borderRadius: 8 },
  filterLabel: { color: '#111827', fontSize: 16, fontWeight: '800' },
  filterLabelActive: { color: '#fff' },
  gridIcon: { color: '#0f172a', fontSize: 18, fontWeight: '900' },
  gridIconActive: { color: '#fff' },
  investorFilterRow: { marginTop: 10, flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 8 },
  investorFilterChip: { minHeight: 34, paddingHorizontal: 12, borderRadius: 999, backgroundColor: '#fff', borderWidth: 1, borderColor: '#e2e8f0', alignItems: 'center', justifyContent: 'center' },
  investorFilterChipActive: { backgroundColor: '#0f766e', borderColor: '#0f766e' },
  investorFilterText: { color: '#334155', fontSize: 12, fontWeight: '900' },
  investorFilterTextActive: { color: '#fff' },
  message: { marginTop: 10, color: '#075985', textAlign: 'right', fontWeight: '800', backgroundColor: '#eff6ff', borderRadius: 14, paddingVertical: 9, paddingHorizontal: 12, overflow: 'hidden' },
  listArea: { marginTop: 20 },
  investmentCard: { backgroundColor: '#fff', borderRadius: 21, marginBottom: 14, paddingVertical: 14, paddingHorizontal: 14, borderWidth: 1, borderColor: '#edf0f2', shadowColor: '#111827', shadowOpacity: 0.06, shadowRadius: 14, shadowOffset: { width: 0, height: 7 }, elevation: 2 },
  investmentCardActive: { backgroundColor: '#f0fdf4', borderColor: '#bbf7d0' },
  investmentCardOverdue: { backgroundColor: '#fff7ed', borderColor: '#fed7aa' },
  investmentCardReceived: { backgroundColor: '#eff6ff', borderColor: '#bfdbfe' },
  cardMainRow: { minHeight: 100, flexDirection: 'row-reverse', alignItems: 'center' },
  itemCenter: { flex: 1, alignItems: 'flex-end', justifyContent: 'center', paddingRight: 4, paddingLeft: 8 },
  itemTitle: { color: '#06111f', fontSize: 18, fontWeight: '900', textAlign: 'right', maxWidth: '100%' },
  investorNamesRow: { marginTop: 8, flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 5, justifyContent: 'flex-start' },
  investorNameChip: { backgroundColor: 'rgba(255,255,255,0.72)', borderWidth: 1, borderColor: 'rgba(15,118,110,0.14)', borderRadius: 999, paddingHorizontal: 9, paddingVertical: 4 },
  investorNameText: { color: '#0f766e', fontSize: 11, fontWeight: '900' },
  dateRow: { marginTop: 14, flexDirection: 'row-reverse', alignItems: 'center', gap: 5 },
  calendarIcon: { color: '#4b5563', fontSize: 12, fontWeight: '900' },
  dateText: { color: '#374151', fontSize: 11.5, fontWeight: '600', textAlign: 'right' },
  inlineCheck: { width: 19, height: 19, borderRadius: 10, borderWidth: 1.5, borderColor: '#0d7772', color: '#0d7772', textAlign: 'center', fontWeight: '900', lineHeight: 16, marginRight: 4 },
  itemLeft: { width: 150, alignSelf: 'stretch', justifyContent: 'space-between', alignItems: 'flex-start', paddingVertical: 1 },
  amountLine: { flexDirection: 'row', alignItems: 'baseline', gap: 5 },
  currencySmall: { color: '#0f172a', fontSize: 11.5, fontWeight: '800' },
  amountValue: { color: '#0a1424', fontSize: 17, fontWeight: '900' },
  profitText: { color: '#008b54', fontSize: 12.5, fontWeight: '800', textAlign: 'left' },
  profitOverdue: { color: '#f05a12' },
  profitReceived: { color: '#1673ca' },
  actionsRow: { flexDirection: 'row', gap: 9, marginTop: 13, alignItems: 'center' },
  circleAction: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#fff', borderWidth: 1, borderColor: '#e8edf1', alignItems: 'center', justifyContent: 'center' },
  disabledAction: { opacity: 0.5 },
  expandedArea: { marginTop: 12, backgroundColor: 'rgba(255,255,255,0.86)', borderRadius: 16, borderWidth: 1, borderColor: '#e2e8f0', padding: 12 },
  detailText: { color: '#475569', textAlign: 'right', fontWeight: '800', marginTop: 4 },
  allocBox: { marginTop: 9, backgroundColor: '#fff', borderRadius: 13, padding: 10, borderWidth: 1, borderColor: '#e2e8f0' },
  allocTitle: { color: '#0f172a', fontWeight: '900', textAlign: 'right', marginBottom: 5 },
  allocText: { color: '#475569', textAlign: 'right', marginTop: 4, fontSize: 12, fontWeight: '700' },
  investorsCard: { marginTop: 20, backgroundColor: '#fff', borderRadius: 22, padding: 16, borderWidth: 1, borderColor: '#edf0f2' },
  panelTitle: { color: '#0f172a', fontSize: 20, fontWeight: '900', textAlign: 'right', marginBottom: 12 },
  investorRow: { marginTop: 8, flexDirection: 'row-reverse', gap: 10, alignItems: 'center', backgroundColor: '#f8fafc', borderRadius: 17, padding: 11 },
  investorAvatar: { width: 42, height: 42, borderRadius: 15, backgroundColor: '#0f766e', alignItems: 'center', justifyContent: 'center' },
  investorAvatarText: { color: '#fff', fontWeight: '900', fontSize: 16 },
  investorInfo: { flex: 1, alignItems: 'flex-end' },
  investorName: { color: '#0f172a', fontWeight: '900', textAlign: 'right' },
  investorText: { color: '#64748b', textAlign: 'right', marginTop: 3, fontSize: 12, fontWeight: '800' },
  investorScreen: { marginTop: 16, backgroundColor: '#fff', borderRadius: 24, padding: 16, borderWidth: 1, borderColor: '#e2e8f0' },
  investorScreenTitle: { color: '#0f172a', fontSize: 22, fontWeight: '900', textAlign: 'right' },
  investorScreenSubtitle: { marginTop: 4, color: '#64748b', fontSize: 12, fontWeight: '800', textAlign: 'right' },
  investorPaymentCard: { marginTop: 12, backgroundColor: '#f8fafc', borderRadius: 18, padding: 12, borderWidth: 1, borderColor: '#e2e8f0' },
  investorPaymentTitle: { color: '#0f172a', fontSize: 15, fontWeight: '900', textAlign: 'right' },
  investorPaymentInput: { marginTop: 9, backgroundColor: '#fff', borderWidth: 1, borderColor: '#dbe4ea', borderRadius: 14, paddingVertical: 10, paddingHorizontal: 12, color: '#0f172a', fontWeight: '900', textAlign: 'right' },
  investorPaymentButton: { marginTop: 9, backgroundColor: '#0f766e', borderRadius: 14, paddingVertical: 11, alignItems: 'center' },
  investorPaymentButtonText: { color: '#fff', fontWeight: '900', fontSize: 13 },
  investorPaymentMeta: { marginTop: 5, color: '#64748b', fontSize: 11, fontWeight: '800', textAlign: 'right' },
  emptyCard: { marginTop: 12, backgroundColor: '#fff', borderRadius: 22, padding: 22, borderWidth: 1, borderColor: '#edf0f2', alignItems: 'center' },
  emptyIcon: { color: '#0f766e', fontSize: 28, fontWeight: '900', marginBottom: 8 },
  emptyTitle: { color: '#0f172a', fontSize: 18, fontWeight: '900', textAlign: 'center' },
  emptyText: { marginTop: 6, color: '#64748b', textAlign: 'center', fontWeight: '800' },
  bottomWrap: { position: 'absolute', left: 16, right: 16, bottom: 7, height: 82, alignItems: 'center', justifyContent: 'flex-end' },
  bottomBar: { height: 66, width: '100%', borderRadius: 27, backgroundColor: '#fff', borderWidth: 1, borderColor: '#e7ecef', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', paddingHorizontal: 8, shadowColor: '#111827', shadowOpacity: 0.12, shadowRadius: 18, shadowOffset: { width: 0, height: 7 }, elevation: 9 },
  bottomItem: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  centerSpace: { flex: 0.88 },
  bottomIcon: { color: '#4b5563', fontSize: 25, fontWeight: '900', lineHeight: 25 },
  bottomIconActive: { color: '#0f766e' },
  bottomLabel: { marginTop: 4, color: '#4b5563', fontSize: 12, fontWeight: '700' },
  bottomLabelActive: { color: '#0f766e', fontWeight: '900' },
  centerFab: { position: 'absolute', bottom: 26, width: 74, height: 74, borderRadius: 37, backgroundColor: '#007371', alignItems: 'center', justifyContent: 'center', borderWidth: 6, borderColor: '#f4f8f8', shadowColor: '#003f44', shadowOpacity: 0.32, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 10 },
  centerFabIcon: { color: '#fff', fontSize: 21, fontWeight: '900', lineHeight: 20 },
  centerFabBars: { color: '#fff', fontSize: 19, fontWeight: '900', lineHeight: 20, marginTop: -1 },
});
